global:
  resolve_timeout: 5m

route:
  receiver: all-channels
  group_by: ["alertname", "job", "severity"]
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 2h

receivers:
  - name: all-channels
    slack_configs:
      - api_url: "__SLACK_WEBHOOK_URL__"
        channel: "#all-shahd"
        username: "Alertmanager"
        send_resolved: true
        title: "[{{ .Status | toUpper }}] {{ .CommonLabels.alertname }}"
        text: "{{ range .Alerts }}{{ .Annotations.summary }}\n{{ .Annotations.description }}\n{{ end }}"

    telegram_configs:
      - bot_token: "__TELEGRAM_BOT_TOKEN__"
        chat_id: __TELEGRAM_CHAT_ID__
        parse_mode: "HTML"
        send_resolved: true
        message: "<b>[{{ .Status | toUpper }}]</b> {{ .CommonLabels.alertname }}\n{{ range .Alerts }}{{ .Annotations.summary }}\n{{ .Annotations.description }}\n{{ end }}"
